elements = {
    'search': ['ID', 'search'],
    'action': ['XPATH', '//*[@id="search-form-property"]/div[3]/div[2]/div/button'],
    'select_buy': ['XPATH', '//*[@id="search-form-property"]/div[3]/div[2]/div/div/ul/li[2]'],
    'property_type': ['XPATH', '//*[@id="search-form-property"]/div[4]/div/div[1]/div/button'],
    'select_villa': ['XPATH', '//*[@id="search-form-property"]/div[4]/div/div[1]/div/div/ul/li[3]'],
    'min_beds_button': ['XPATH', '//*[@id="bedroom_group"]/div[1]/div/button'],
    'select_3_beds': ['XPATH', '//*[@id="bedroom_group"]/div[1]/div/div/ul/li[5]'],
    'max_beds_button': ['XPATH', '//*[@id="bedroom_group"]/div[2]/div/button'],
    'select_7_beds': ['XPATH', '//*[@id="bedroom_group"]/div[2]/div/div/ul/li[9]'],
    'city': ['NAME', 'q', 0],
    'is_result': ['XPATH', '//*[@id="serp-nav"]/div[2]/div[2]'],
    'sort_results': ['XPATH', '//*[@id="serp-nav"]/div[1]/div/div/button'],
    'price_low': ['XPATH', '//*[@id="serp-nav"]/div[1]/div/div/div/ul/li[3]'],
    'smart_ads': ['CLASS_NAME', 'smart-ads-list', 0],
    'results_section': ['ID', 'serp'],
    'results_data_list': ['CLASS_NAME', 'listing-content', -1],

    'find_agent': ['XPATH', '//*[@id="header"]/div[1]/nav/ul/li[4]/a'],
    'first_agent': ['XPATH', '//*[@id="find-an-agent"]/form/div[2]/div[2]/div[1]/a'],
    'user_info' : ['CLASS_NAME', 'user-info', 0],
    'user_personal_info': ['CLASS_NAME', 'user-personal-info', 0],
    'view_profile': ['LINK_TEXT', 'View profile'],
    'company_name': ['CLASS_NAME', 'company-name', 0],
    'call_agent': ['CLASS_NAME', 'call-agent', 0],
    'about_me_button': ['XPATH', '//*[@id="find-an-agent"]/div/div[3]/div[1]/section/div[1]/button[1]'],
    'about_me': ['CLASS_NAME', 'user-tab-about-me', 0],
    'arabic': ['CLASS_NAME', 'ar', 0],
    'language': ['XPATH', '//*[@id="find-an-agent"]/form/div[1]/div/div/div[3]/div/div[2]/div[2]/div/button'],
    'language_list': ['XPATH', '//*[@id="find-an-agent"]/form/div[1]/div/div/div[3]/div/div[2]/div[2]/div/div/ul'],
    'search_form': ['CLASS_NAME', 'search-form', 0],
    'count_agents': ['CLASS_NAME', 'serp-h1', 0],
    'nationality': ['XPATH', '//*[@id="find-an-agent"]/form/div[1]/div/div/div[2]/div[3]/div/button'],
    'india': ['XPATH', '//*[@id="find-an-agent"]/form/div[1]/div/div/div[2]/div[3]/div/div/ul/li[33]'],
}

